#!/usr/bin/env zsh
#
# === {{CMD}} watch|run
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION="watch"
else
  local +x ACTION=$1; shift
fi

case "$ACTION" in

  watch)
    local +x cmd="da_html_escape.cr specs run $@"
    ${=cmd} || :
    process watch "-r bin -r sh -r src -r specs" "$cmd"
    ;;

  run)
    reset
    mkdir -p tmp/out

    sh_color ORANGE "=== {{Compiling}} specs..."
    my_crystal __ build specs/specs.cr -o tmp/out/specs

    sh_color ORANGE "=== {{Running}}: tmp/da_html_escape.specs $@ "
    time tmp/out/specs $@

    sh_color GREEN "=== {{DONE}} ===" >&2
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

