#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION="run"
else
  local +x ACTION=$1; shift
fi

case "$ACTION" in

  watch)
    local +x cmd="html_escape.cr specs run $@"
    ${=cmd} || :
    process watch "-r bin -r sh -r src -r specs" "$cmd"
    ;;

  run)
    reset
    mkdir -p tmp/

    sh_color ORANGE "=== Compiling specs..."
    my_crystal __ build specs/da_html_escape.cr -o tmp/da_html_escape.specs

    sh_color ORANGE "=== {{Running}}: tmp/da_html_escape.specs $@ "
    time tmp/da_html_escape.specs $@

    sh_color GREEN "=== {{DONE}} ===" >&2
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

